- hosts: controlplane1
  gather_facts: True
  become: True

  tasks:

    - name: init cluster
      shell: "{{ 'kubeadm init --apiserver-advertise-address=' + hostvars['controlplane1']['ansible_all_ipv4_addresses'][-1] }}"
      args:
        creates: /etc/kubernetes/manifests/kube-scheduler.yaml
      register: init_output

    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command



- hosts: worker_hosts
  gather_facts: False
  become: True

  tasks:
      - name: show join command
        debug:
          var: hostvars['controlplane1']['join_command'].stdout
      - name: run join command
        shell: "{{ hostvars['controlplane1']['join_command'].stdout }}"
