---
# tasks file for kubernetes_control_plane_init

- name: enable kubelet
  systemd:
    name: kubelet
    enabled: True
    state: started

- name: pull images
  shell: kubeadm config images pull && touch /root/kubeadm.images
  args:
    creates: /root/kubeadm.images
  become: True
